# Generated by Django 5.2.6 on 2026-03-04 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('note', models.TextField(blank=True)),
                ('actor', models.CharField(blank=True, max_length=128)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-acted_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=64, unique=True)),
                ('standardized_name', models.CharField(max_length=255)),
                ('category_group', models.CharField(max_length=128)),
                ('pic_owner', models.CharField(blank=True, max_length=128)),
                ('is_disabled', models.BooleanField(default=False)),
                ('operational_status', models.CharField(choices=[('IN_USE', 'In Use'), ('STANDBY', 'Standby'), ('BROKEN', 'Broken')], default='IN_USE', max_length=20)),
                ('inspection_required', models.BooleanField(default=True)),
                ('inspection_expiry_date', models.DateField(blank=True, null=True)),
                ('pm_required', models.BooleanField(default=True)),
                ('pm_next_due_date', models.DateField(blank=True, null=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=8)),
                ('expected_eol_at', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('imei', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.location')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.vendor')),
            ],
            options={
                'ordering': ['-updated_at', 'asset_code'],
            },
        ),
    ]
