# Generated by Django 5.2.6 on 2026-03-04 13:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('MAIN', 'Main'), ('ACCESSORY', 'Accessory'), ('TOOL', 'Tool')], default='MAIN', max_length=16),
        ),
        migrations.AddField(
            model_name='asset',
            name='barcode',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='inspection_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ops_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='pm_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_class',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='asset',
            name='service_contract_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='year_of_manufacture',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='after_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='before_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='field_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=128)),
                ('code_or_serial', models.CharField(blank=True, max_length=128)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('MISSING', 'Missing'), ('DAMAGED', 'Damaged')], default='OK', max_length=16)),
                ('mandatory', models.BooleanField(default=False)),
                ('last_verified_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=32)),
                ('file_name', models.CharField(max_length=255)),
                ('related_to', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_code', models.CharField(max_length=64)),
                ('compliance_type', models.CharField(choices=[('CALIBRATION', 'Calibration'), ('VERIFICATION', 'Verification'), ('SAFETY_TEST', 'Safety Test'), ('INSPECTION', 'Inspection')], max_length=16)),
                ('performed_by', models.CharField(default='INTERNAL', max_length=32)),
                ('performed_at', models.DateField()),
                ('next_due_at', models.DateField(blank=True, null=True)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], default='PASS', max_length=8)),
                ('certificate_name', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='assets.asset')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=64)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('custodian_after', models.CharField(max_length=128)),
                ('handover_date', models.DateField()),
                ('accessories_summary', models.CharField(blank=True, max_length=255)),
                ('signed', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='assets.asset')),
            ],
            options={
                'ordering': ['-handover_date'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_code', models.CharField(max_length=64)),
                ('reported_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('symptom', models.CharField(max_length=255)),
                ('priority', models.CharField(default='MEDIUM', max_length=16)),
                ('root_cause', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('CONFIRMED', 'Confirmed'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='REPORTED', max_length=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='assets.asset')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='MovementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField()),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('action_by', models.CharField(max_length=128)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='assets.asset')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='PartConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_at', models.DateField()),
                ('wo_code', models.CharField(blank=True, max_length=64)),
                ('part_code', models.CharField(max_length=64)),
                ('part_name', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('batch_info', models.CharField(blank=True, max_length=128)),
                ('issued_store', models.CharField(blank=True, max_length=128)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_consumptions', to='assets.asset')),
            ],
            options={
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_code', models.CharField(max_length=64)),
                ('wo_type', models.CharField(choices=[('PM', 'PM'), ('REPAIR', 'Repair'), ('CALIBRATION', 'Calibration'), ('INSPECTION', 'Inspection')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('technician', models.CharField(blank=True, max_length=128)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('checklist_summary', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='OPEN', max_length=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='assets.asset')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
